<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.559" timestamp="2025-09-19T01:47:31.022069-03:00" hostname="note-dago"><testcase classname="" name="ai-ml.model-registry.tests.test_dashboard_app" time="0.000"><error message="collection failure">ImportError while importing test module '/home/dcm/Projetos/cluster-ai/ai-ml/model-registry/tests/test_dashboard_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../venv/lib/python3.13/site-packages/_pytest/python.py:498: in importtestmodule
    mod = import_path(
../../venv/lib/python3.13/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
../../venv/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/test_dashboard_app.py:7: in &lt;module&gt;
    from ai_ml.model_registry.dashboard import app as flask_app
E   ModuleNotFoundError: No module named 'ai_ml'</error></testcase></testsuite></testsuites>